### ISSUE TITLE
Donate - Not Hooked up to Paypal

### ISSUE THREAD

**Issue by cphoover** [cphoover/MissionToHeal#18]
Donate - Not Hooked up to Paypal

**Comment by cphoover** [comment]
@gwenbultema 

Looking at Paypal api for onsite forms with redirect to paypal for payment (on-site buttons) . It appears they have a subscript button for recurring payments. But I'm not seeing a way to add a custom amount for a recurring subscription (I could be wrong I'm contacting their support).

Two thoughts...

We are either ok with having a fixed amount for the subscription... (e.g $20/m, $60/m, $100/m), and allow custom amounts for one time payments only.

Or we can look at other payment APIs that may have better support for example stripe.com.

**Comment by cphoover** [comment]
I just deleted my last comment because it appears to be wrong :P

**Comment by cphoover** [comment]
@gwenbultema 
Donate page has been hooked up to paypal, and I succesfully made two donations for recurring and one time donations.

Please test it out (you can refund payments on paypal.com for testing): 
http://beta.missiontoheal.org/donate.php

**Comment by gwenbultema** [comment]
Beautiful stuff, @cphoover! I didn't go all the way through the process, but saw that everything was working well. Thanks! Getting close!
